### ISSUE TITLE
samsung UE40F6400 volume control

### ISSUE THREAD

**Issue by simoneras** [mmende/homebridge-samsungtv-control2#12]
hi everyone, how do i turn on volume control. thank you

**Comment by mmende** [comment]
Volume is implemented but doesn't show up at the moment. It however shows up in the homebridge accessories tab for me. I still have to figure out why iOS isn't showing the speaker service.

**Comment by simoneras** [comment]
hi, I also see it as accessories in Homebridge but not on ios. thank you

**Comment by mmende** [comment]
I have the theory that iOS requires some other characteristics like [CurrentMediaState](https://developers.homebridge.io/#/characteristic/CurrentMediaState) before it will show the volume characteristics. Unfortunately I didn't find any more documentation concerning this topic in the hombridge docs or apples homekit documentation yet.

**Comment by mmende** [comment]
I just figured out that I can control the volume with the iPhone hardware buttons when in control center -> remote -> tv selected on top... I still don't know how to toggle mute in the remote app however. The [source](https://www.npmjs.com/package/homebridge-bravia) for this info also says that the home app just doesn't show the tv speaker accessory like other apps do. I might add an option to add a "lightbulb" accessory or so to be able to control the volume/mute directly in the home app like other plugins do.

**Comment by ggroel** [comment]
the native accessory of apple tv 4 has volume control ... maybe you can investigate on that side ...

Gastón

**Comment by ggroel** [comment]
Maybe it will help

https://developer.apple.com/documentation/mediaplayer/mpvolumeview

Gastón

**Comment by simoneras** [comment]
in node-red Linked service "TelevisionSpeaker" e Characteristic : 
{
    "VolumeControlType":1,
    "VolumeSelector":true
}

so I see it in the control center with output {"RemoteKey":4} UP; {"RemoteKey":5} DOWN; {"RemoteKey":7}DX; {"RemoteKey":6} SX

IF YOU CAN USE IT

**Comment by simoneras** [comment]
now works!!!

**Comment by mmende** [comment]
Nice... A more fine grained volume control is not accessible in iOS yet unfortunately. However it is implemented theoretically in this plugin. I hope iOS 14 will bring volume controls for tv's.
