### ISSUE TITLE
Is a Token the same as the UUID?

### ISSUE THREAD

**Issue by jchhenderson** [mmende/homebridge-samsungtv-control2#21]
Hi,

I am a little confused!

My logs tell me to issue the npx command, but the very next line gives me the UUID (which I have put into my config).

**Question:** Is the paring token the same thing as the UUID?

When I run the pairing command, I get the following error:
```
Ok... sending the pairing request to your tv. Please click allow when asked
(node:45177) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.

/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:66
                throw new Error('Error send Key');
                ^

Error: Error send Key
    at /usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:66:23
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/lib/samsung.js:299:17)
    at WebSocket.emit (events.js:315:20)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-samsungtv-control/node_modules/samsung-tv-control/node_modules/ws/lib/websocket.js:551:15)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Meanwhile, I cannot select any of my custom inputs.

**Question:** What am I doing wrong?

cheers!
James.

**Comment by mmende** [comment]
Hi.
No the pairing token is not the same as the usn (uuid). The usn is being used to identify the tv via upnp (because the ip might change over time). The pairing token is required if your tv requires authentication to control it (which most newer models do). Otherwise the tv might be visible in homebridge but not be controllable because the plugin is not allowed to yet. Did you try the other pairing methods?

**Comment by jchhenderson** [comment]
agh - great, thanks for explaining.  ...where do I put/use the token?

I didn't try the other pairing methods because I thought I had an error that would a problem for all methods.  I will try it now and let you know.

cheers!

**Comment by mmende** [comment]
No problem. If you manage to get a token you add it like this:

```json
{
  "platform": "SamsungTVControl",
  "devices": [
    {
      "usn": "uuid:a7001fbe-c776-11ea-87d0-0242ac130003",
      "token": "eyJzZXNzaW9uSWQiOjQyLCJhZXNLZXkiOiJZb3UgcmVhbGx5IGRlY29kZWQgdGhpcz8g8J+YiSJ9==",
      "name": "Bedroom TV"
    }
  ]
}
```

I unfortunately was not able to catch all errors in the pairing scripts yet. Therefore the output is still a bit ugly here and there.

**Comment by jchhenderson** [comment]
no worries about ugly :-)

Both pair1 and pair2 came back with "Error send Key".

Legacy did not, but the TV is not in my house (I am remoting into my parent's Mac to do this) so not sure if that worked or not.  Will find out later.

...but:
I assume - if legacy works, I won't need a token??
As my config is currently tokenless that would mean legacy also does not work??

**Comment by mmende** [comment]
If legacy works no token is required. However the legacy protocol is only supported until ~2013 as far as I know.

**Comment by jchhenderson** [comment]
agh, my parents got their TV only last year.

**Comment by mmende** [comment]
Ok... in this case pair1 or pair2 might be your only options. If both of them don't work the tv unfortunately might not be supported by one of the libraries being used to control the tv.

**Comment by jchhenderson** [comment]
agh.  Is there anything I can do?

...like the face mask, by the way!

**Comment by mmende** [comment]
Thanks. For pair2 you could also try port 8001 by adding ` --port 8001`

**Comment by jchhenderson** [comment]
yes, I did try that as well (sorry I did not mention not before).

**Comment by mmende** [comment]
No problem. Then I guess it isn't supported yet unfortunately. The thing with the remote control libraries is that samsung isn't posting any documentation on how to accomplish that. It's all reverse engineered. Furthermore the implementation even changed heavily over time what makes it even worse.
