### ISSUE TITLE
Can't add to HOOBS/Homekit? "The requested platform was not registered by any plugin."

### ISSUE THREAD

**Issue by Fofer** [mmende/homebridge-samsungtv-control2#30]
Hi and thanks for making this plug in. I'm excited about getting it running and feel I am very very close.  I followed the instructions and ran the pairing command with my TV, confirmed it worked with the "mute" test and then pasted the token into the configuration of the Samsungtv Control plugin in HOOBS.  However I can't get it to appear there as an accessory and I can't add it in the iOS Home app as an Accessory that "I don't have a code for."  It doesn't show as a "nearby accessory."  

I've rebooted the HOOBS server, the AppleTV, the TV itself as well as the router.  Everything else is working, just not this one.  What's am I missing?   This is the relevant error from my logs:

```
9/13/2020, 5:41:24 PM The requested platform "SamsungTVControl" was not registered by any plugin.
9/13/2020, 5:41:24 PM Your config.json is requesting the platform "SamsungTVControl" which has not been published by any installed plugins.
```

And this is the relevant bit from my config.json, I just changed my usn and token a bit for security. 

```
{
    "platform": "SamsungTVControl",
    "devices": [
        {
            "usn": "uuid:85439306-a10c-42ba-b6c5-911823fc4b8b",
            "token": "eyJzPXNzaW9uYUBiOiIyIiwiYWVzQ2V5IjoiOTU4NWY5YTY1ZDI3NjlhYjlkMDJhYmEwMDEyMTRhOTEifQ==",
            "name": "Living Room TV",
            "inputs": [
                {
                    "name": "HDMI",
                    "keys": "hdmi"
                },
                {
                    "name": "ZDF HD",
                    "keys": "102"
                },
                {
                    "name": "Sleep 30m",
                    "keys": "tools,down*3,enter,down,enter,return"
                },
                {
                    "name": "Open YouTube",
                    "keys": "YouTube"
                }
            ]
        }
    ]
}
```

 I'm new to this and still learning and would appreciate any assistance.

**Comment by mmende** [comment]
I actually have never heard of hoobs bevore but it looks really cool... I guess this issue is the same as #22, however I'll leave it open until the other issue is resolved.

**Comment by nidy86** [comment]
Hi @mmende,

Thanks for implementing this plugin. Nice Job done!

I think I've got the answer for this issue. 

Change your index.ts file like this:
`import { API } from 'homebridge'
import { PLATFORM_NAME, PLUGIN_NAME } from './settings'
import { SamsungTVHomebridgePlatform } from './platform'

/**
 * This method registers the platform with Homebridge
 */
export = (api: API) => {
  api.registerPlatform(PLUGIN_NAME, PLATFORM_NAME, SamsungTVHomebridgePlatform)
}
`

now the plugin will be found. 

And for the impatient ones, here is a little work around:

1. Login to hoobs and open the terminal
2. enter "cd ../node_modules/homebridge-samsungtv-control/dist" to change to the right dir
3. enter nano index.js
4. now change following line:
`api.registerPlatform(settings_1.PLATFORM_NAME, platform_1.SamsungTVHomebridgePlatform);`
to
`api.registerPlatform(**settings_1.PLUGIN_NAME**, settings_1.PLATFORM_NAME, platform_1.SamsungTVHomebridgePlatform);`

**Comment by mmende** [comment]
Thank you very much for the hint. I'll see if I can add and test it later that day.

**Comment by mmende** [comment]
New version (v2.0.0) is published. @Fofer please let me know if this fixed your problem. And thanks again @nidy86

**Comment by Fofer** [comment]
Wow! Yes, with this fix I was finally able to add my 2015 Samsung TV (model UN78JS8600F) to HomeKit. I am now experimenting with the various commands/inputs to see which ones work, and how to best use them with my set. I'm sure I'll have some other questions soon, but this is a fantastic breakthrough. Thank you so much @mmende and @nidy86, it's very appreciated.

**Comment by frios** [comment]
This is working great. I am installing it under HOOBS. All good until I try to add the accessory in Home app. It is asking for theHomekit Setup code. Your instructions ay to use the Config > Bridge > Pin. Where do I find that?

**Comment by Fofer** [comment]
It's in your HOOBS configuration page.   Click the "gear" icon at the bottom left and click "Apple Home."  The HomeKIt setup code (PIN) is at the bottom of that page.  I see mine at http://hoobs.local/config/bridge

**Comment by frios** [comment]
Perfect! Thank you!

**Comment by mmende** [comment]
Awesome. I'll close this issue for now as it seems to be solved.
