### ISSUE TITLE
dPad

### ISSUE THREAD

**Issue by Phil7989** [mmende/homebridge-samsungtv-control2#37]
Hi, 

Thank you for this cool HomeKit feature!
In my Home App i cant see the dPad?
What can i do to see it?

Philipp

**Comment by mmende** [comment]
To access the d-pad add the "Apple TV Remote" control element to your control-center in iOS settings . Then open control-center -> remote icon. In this control you should be able to select the tv on top as shown in the in the third image here:

![example images](https://github.com/mmende/homebridge-samsungtv-control2/blob/master/assets/preview.png?raw=true)
