### ISSUE TITLE
Found unparsable model name xxxx for device xxxxx, usn: "uuid:xxxxxxxxxxxxxx". Skipping it.

### ISSUE THREAD

**Issue by TheEngineerGuy** [mmende/homebridge-samsungtv-control2#70]
This message shows up quite often and has essentially taken over the log file. Can I do something to hide it?

`Found unparsable model name (HW-Q80R) for device [AV] Samsung Soundbar Q80R, usn: "uuid:xxxxxxxxxxxxxx". Skipping it.`

**Comment by SeanHama** [comment]
following this issue

**Comment by benfysh** [comment]
Hi, this is still present for non Samsung products in  v2.1.0 for example:

``Found unparsable model name (Philips hue bridge 2015) for device Philips hue (192.168.6.252), usn: "uuid:xxxxxx…". Skipping it.``

Is it possible to have these as a debug entry only? thanks

As a workaround I have commented out [line 83](https://github.com/mmende/homebridge-samsungtv-control2/blob/50ee30cca77ed2d72a70c872b1cb6fa90f90970e/src/utils/detectDevices.ts#L83) in /[src](https://github.com/mmende/homebridge-samsungtv-control2/tree/master/src)/[utils](https://github.com/mmende/homebridge-samsungtv-control2/tree/master/src/utils)/detectDevices.ts

**Comment by TheEngineerGuy** [comment]
Actually, this is still present for non-TV Samsung devices like soundbars as well. Both my LG and Samsung soundbar are still showing up on the logs.

@mmende
