### ISSUE TITLE
Error on updating via Homebridge Config UI X

### ISSUE THREAD

**Issue by 3zero2** [mmende/homebridge-samsungtv-control2#9]
When trying to update via Homebridge Config UI X I am getting the following error. Anyone else or is it just me?

```
USER: homebridge
DIR: /usr/lib
CMD: sudo -E -n npm install homebridge-samsungtv-control@latest

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/mmende/samsung-remote-models-2014-and-newer.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2020-07-25T14_15_06_626Z-debug.log

Command failed. Please review log for details.
```

**Comment by ggroel** [comment]
I have all plugins updated without errors...



Gastón

**Comment by mmende** [comment]
It seems like npm refuses to install this library from github directly. Unfortunately the authors of this library didn't publish it to the npm registry yet, however I also had to change some things to get it work with the homebridge plugin. I therefore just forked it and install the dependency directly from github which is not the best solution. I just didn't want to publish it myself making it look like I developed the library and already opened an issue at the original repo. Maybe I publish it as `samsung-remote-models-2014-and-newer-fork` and link the original repo in the readme to clarify that I am not the developer of this library and just altered it slightly to work with this homebridge plugin. What do you guys think about that?

**Comment by ggroel** [comment]
I’m agree!!!..

Gastón

**Comment by 3zero2** [comment]
Why not submit a pull request?

**Comment by mmende** [comment]
For the modifications sure... the problem however is, that the library is not published to the public registry yet.

**Comment by 3zero2** [comment]
In that case I would proceed as you suggested. Publish as `samsung-remote-models-2014-and-newer-fork` with a link to the original repo in the readme.

**Comment by mmende** [comment]
I just published a new version (v2.0.0-alpha.12). Could you check if the problem still occurs?

**Comment by 3zero2** [comment]
I have managed to install without any issues 🥇

**Comment by mmende** [comment]
Awesome... I am closing this issue for now. If the problem should reappear somehow feel free to reopen the issue or open a new one.
